/* ===== Animations CSS (injectées) ===== */
const animCSS = `
@keyframes catOpac{0%,12%{opacity:0}55%,90%{opacity:1}100%{opacity:0}}
.an .opac{animation:catOpac 4.6s ease-in-out infinite}
@keyframes catSepia{0%,12%{opacity:0}55%,90%{opacity:.8}100%{opacity:0}}
.an .sepia{animation:catSepia 4.6s ease-in-out infinite}
@keyframes refA{0%,42%{opacity:1}52%,100%{opacity:0}} @keyframes refB{0%,42%{opacity:0}52%,95%{opacity:1}100%{opacity:0}}
.an .gemme{animation:refA 5s ease-in-out infinite}.an .gmyo{animation:refB 5s ease-in-out infinite}
@keyframes laserBeam{0%,15%{opacity:0}25%,60%{opacity:1}75%,100%{opacity:0}}
.an .beam{animation:laserBeam 4s linear infinite}.an .beam:nth-child(2){animation-delay:.1s}.an .beam:nth-child(3){animation-delay:.2s}.an .beam:nth-child(4){animation-delay:.3s}.an .beam:nth-child(5){animation-delay:.4s}.an .beam:nth-child(6){animation-delay:.5s}.an .beam:nth-child(7){animation-delay:.15s}
@keyframes ivtMove{0%{transform:translateY(-6px)}26%,44%{transform:translateY(30px)}66%,100%{transform:translateY(-6px)}}
.an .needle{animation:ivtMove 4.2s ease-in-out infinite}
@keyframes ivtDiff{0%,30%{transform:scale(.65);opacity:.4}50%{transform:scale(1.15);opacity:.9}72%,100%{transform:scale(.9);opacity:.6}}
.an .diffuse{animation:ivtDiff 4.2s ease-in-out infinite;transform-box:fill-box;transform-origin:center}
@keyframes tearShow{0%,12%{opacity:0;transform:scale(.4)}20%{opacity:1;transform:scale(1)}100%{opacity:1}}
.an .tear{animation:tearShow 5s ease-in-out infinite;transform-box:fill-box;transform-origin:center}
/* Hero — simulation de conversation avec l'assistant */
.hd{background:#fff;border-radius:16px;width:100%;height:100%;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 6px 20px -12px rgba(13,61,143,.4)}
.hd-head{display:flex;align-items:center;gap:8px;padding:11px 14px;background:linear-gradient(120deg,#1565d8,#0a3d8f);color:#fff;flex:none}
.hd-dot{width:9px;height:9px;border-radius:50%;background:#4ade80;box-shadow:0 0 0 3px rgba(74,222,128,.25)}
.hd-name{font-weight:700;font-size:.9rem}
.hd-on{margin-left:auto;font-size:.7rem;opacity:.85}
.hd-body{flex:1;overflow:hidden;padding:12px;display:flex;flex-direction:column;gap:8px;background:#f5f9ff}
.hd-msg{max-width:84%;padding:8px 11px;border-radius:13px;font-size:.82rem;line-height:1.42;animation:hdIn .3s ease;word-wrap:break-word}
.hd-msg.u{align-self:flex-end;background:linear-gradient(120deg,#1565d8,#0a3d8f);color:#fff;border-bottom-right-radius:4px}
.hd-msg.a{align-self:flex-start;background:#fff;border:1px solid #e6edf6;color:#0d1b2a;border-bottom-left-radius:4px}
@keyframes hdIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
.hd-typ{display:flex;gap:4px;align-items:center;padding:11px}
.hd-typ span{width:6px;height:6px;border-radius:50%;background:#9db4d0;animation:hdBlink 1s infinite}
.hd-typ span:nth-child(2){animation-delay:.15s}.hd-typ span:nth-child(3){animation-delay:.3s}
@keyframes hdBlink{0%,100%{opacity:.3}50%{opacity:1}}
`;
const st=document.createElement('style');st.textContent=animCSS;document.head.appendChild(st);

/* ===== SVG animations ===== */
const SVG={
cataracte:`<svg class="an" viewBox="0 0 280 150"><g><rect x="6" y="42" width="70" height="66" rx="8" fill="#bfe3ff"/><circle cx="28" cy="62" r="10" fill="#fcd34d"/><rect x="6" y="92" width="70" height="16" fill="#86efac"/><polygon points="56,72 46,86 66,86" fill="#dc2626"/><rect class="sepia" x="6" y="42" width="70" height="66" rx="8" fill="#2e1f0c"/><rect x="6" y="42" width="70" height="66" rx="8" fill="none" stroke="#0a3d8f" stroke-width="2"/></g><line x1="78" y1="60" x2="122" y2="72" stroke="#cbd5e1" stroke-width="1.5"/><line x1="78" y1="92" x2="122" y2="80" stroke="#cbd5e1" stroke-width="1.5"/><circle cx="190" cy="75" r="60" fill="#fdeede" stroke="#0a3d8f" stroke-width="3"/><path d="M218 30 A60 60 0 0 1 218 120" fill="none" stroke="#e8743b" stroke-width="6" opacity=".55"/><path d="M132 50 Q118 75 132 100" fill="#dff0ff" stroke="#1565d8" stroke-width="2"/><line x1="134" y1="52" x2="143" y2="60" stroke="#1565d8" stroke-width="4"/><line x1="134" y1="98" x2="143" y2="90" stroke="#1565d8" stroke-width="4"/><ellipse cx="150" cy="75" rx="14" ry="24" fill="#d3e6ff" stroke="#1565d8" stroke-width="2"/><g class="opac"><ellipse cx="150" cy="75" rx="14" ry="24" fill="#4a3a1e"/><ellipse cx="150" cy="75" rx="9.5" ry="18" fill="#241906"/></g></svg>`,
refraction:`<svg class="an" viewBox="0 0 230 155"><g class="gemme"><circle cx="120" cy="72" r="50" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><ellipse cx="82" cy="72" rx="9" ry="19" fill="#cfe2ff" stroke="#1565d8" stroke-width="2"/><path d="M165 40 A50 50 0 0 1 165 104" fill="none" stroke="#16a34a" stroke-width="4"/><path d="M22 56 L82 67 L164 72" fill="none" stroke="#f0a500" stroke-width="2"/><path d="M22 88 L82 77 L164 72" fill="none" stroke="#f0a500" stroke-width="2"/><circle cx="164" cy="72" r="5" fill="#16a34a"/><text x="115" y="148" text-anchor="middle" class="lbl" fill="#0f766e">Emmétrope — net sur la rétine</text></g><g class="gmyo"><ellipse cx="116" cy="72" rx="64" ry="50" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><ellipse cx="68" cy="72" rx="9" ry="19" fill="#cfe2ff" stroke="#1565d8" stroke-width="2"/><path d="M178 40 A50 50 0 0 1 178 104" fill="none" stroke="#16a34a" stroke-width="4"/><path d="M14 56 L68 67 L120 72" fill="none" stroke="#f0a500" stroke-width="2"/><path d="M14 88 L68 77 L120 72" fill="none" stroke="#f0a500" stroke-width="2"/><circle cx="120" cy="72" r="5" fill="#dc2626"/><text x="115" y="148" text-anchor="middle" class="lbl" fill="#b91c1c">Myope — l'œil s'allonge, foyer en avant</text></g></svg>`,
laser:`<svg class="an" viewBox="0 0 200 150"><path d="M30 118 Q100 22 170 118" fill="none" stroke="#0a3d8f" stroke-width="2" opacity=".25" stroke-dasharray="4 4"/><path stroke="#16b8a6" stroke-width="4" fill="none" stroke-linecap="round"><animate attributeName="d" dur="4s" repeatCount="indefinite" values="M30 118 Q100 24 170 118;M30 118 Q100 60 170 118;M30 118 Q100 60 170 118;M30 118 Q100 24 170 118" keyTimes="0;0.45;0.8;1" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/></path><g stroke="#dc2626" stroke-width="2" stroke-linecap="round"><line class="beam" x1="55" y1="0" x2="55" y2="78"/><line class="beam" x1="70" y1="0" x2="70" y2="64"/><line class="beam" x1="85" y1="0" x2="85" y2="52"/><line class="beam" x1="100" y1="0" x2="100" y2="48"/><line class="beam" x1="115" y1="0" x2="115" y2="52"/><line class="beam" x1="130" y1="0" x2="130" y2="64"/><line class="beam" x1="145" y1="0" x2="145" y2="78"/></g><text x="100" y="142" text-anchor="middle" class="lbl" fill="#0a3d8f">LASIK</text></svg>`,
keratocone:`<svg class="an" viewBox="0 0 200 150"><path d="M150 35 a70 70 0 1 0 0 80" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="95" cy="75" r="13" class="pupil"/><circle cx="95" cy="75" r="26" fill="none" stroke="#1565d8" stroke-width="2" opacity=".5"/><path fill="none" stroke="#16b8a6" stroke-width="5" stroke-linecap="round"><animate attributeName="d" dur="3.6s" repeatCount="indefinite" values="M150 40 Q176 75 150 110;M150 40 Q205 75 150 110;M150 40 Q176 75 150 110" keyTimes="0;0.5;1" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1"/></path></svg>`,
ivt:`<svg class="an" viewBox="0 0 200 150"><g class="needle"><rect x="91" y="0" width="18" height="28" rx="3" fill="#cfe2ff" stroke="#1565d8" stroke-width="2"/><line x1="100" y1="28" x2="100" y2="60" stroke="#94a3b8" stroke-width="3"/></g><path d="M50 60 Q64 47 82 51" fill="none" stroke="#0a3d8f" stroke-width="3" stroke-linecap="round"/><circle cx="100" cy="90" r="52" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="100" cy="90" r="35" fill="#eaf3ff"/><circle class="diffuse" cx="100" cy="90" r="14" fill="#a9d2ff"/></svg>`,
decollement:`<svg class="an" viewBox="0 0 240 150"><circle cx="140" cy="75" r="62" fill="#fdeede" stroke="#0a3d8f" stroke-width="3"/><path d="M84 48 Q70 75 84 102" fill="#dff0ff" stroke="#1565d8" stroke-width="2"/><ellipse cx="96" cy="75" rx="11" ry="20" fill="#d3e6ff" stroke="#1565d8" stroke-width="1.5"/><path d="M172 26 A62 62 0 0 1 172 124" fill="none" stroke="#e8743b" stroke-width="7" opacity=".3"/><path class="tear" d="M176 44 l4 -7 l3 8 l6 -3 l-2 9 l-8 -2 z" fill="#f97316" stroke="#b91c1c" stroke-width="1.4"/><path fill="#f3a06a" fill-opacity=".5" stroke="#d9542a" stroke-width="2.5" stroke-opacity=".85" stroke-linejoin="round"><animate attributeName="d" dur="6.5s" repeatCount="indefinite" values="M176 48 C152 70 152 96 122 102 C152 106 170 112 176 120 Z;M176 48 C140 64 162 98 110 98 C152 110 170 114 176 120 Z;M176 48 C154 72 144 94 116 106 C150 100 170 110 176 120 Z;M176 48 C140 64 162 98 110 98 C152 110 170 114 176 120 Z;M176 48 C152 70 152 96 122 102 C152 106 170 112 176 120 Z" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" keySplines="0.42 0 0.58 1;0.42 0 0.58 1;0.42 0 0.58 1;0.42 0 0.58 1"/></path></svg>`,
strabisme:`<svg class="an" viewBox="0 0 230 130"><ellipse cx="64" cy="60" rx="48" ry="31" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="64" cy="60" r="17" class="iris"/><circle cx="64" cy="60" r="7.5" class="pupil"/><ellipse cx="166" cy="60" rx="48" ry="31" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="192" cy="60" r="17" class="iris"/><circle cx="192" cy="60" r="7.5" class="pupil"/></svg>`,
glaucome:`<svg class="an" viewBox="0 0 200 150"><circle cx="100" cy="75" r="60" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="100" cy="75" r="34" class="iris"/><circle cx="100" cy="75" r="14" class="pupil"/><g stroke="#dc2626" stroke-width="2.5" stroke-linecap="round"><path d="M100 26 l0 -10"><animate attributeName="opacity" dur="3s" values="0;1;0" repeatCount="indefinite"/></path><path d="M149 75 l10 0"><animate attributeName="opacity" dur="3s" values="0;1;0" begin="0.4s" repeatCount="indefinite"/></path><path d="M51 75 l-10 0"><animate attributeName="opacity" dur="3s" values="0;1;0" begin="0.8s" repeatCount="indefinite"/></path></g><text x="100" y="142" text-anchor="middle" class="muted">Pression oculaire élevée</text></svg>`,
eyelid:`<svg viewBox="0 0 200 150"><path d="M36 82 Q100 40 164 82" fill="none" stroke="#0a3d8f" stroke-width="3"/><path d="M36 82 Q100 118 164 82" fill="#eaf3ff" stroke="#0a3d8f" stroke-width="3"/><circle cx="100" cy="82" r="18" class="iris"/><circle cx="100" cy="82" r="8" class="pupil"/><circle cx="122" cy="54" r="11" fill="#fde68a" stroke="#b45309" stroke-width="2.4"/></svg>`,
redeye:`<svg viewBox="0 0 200 150"><ellipse cx="100" cy="75" rx="72" ry="34" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="100" cy="75" r="23" class="iris"/><circle cx="100" cy="75" r="10" class="pupil"/><g stroke="#dc2626" stroke-width="2.2" fill="none" stroke-linecap="round"><path d="M30 68 q20 5 38 7"/><path d="M32 86 q22 -3 38 -5"/><path d="M170 70 q-20 5 -38 6"/><path d="M168 88 q-22 -3 -38 -4"/></g></svg>`,
macula:`<svg viewBox="0 0 200 150"><circle cx="100" cy="75" r="62" fill="#fdeede" stroke="#0a3d8f" stroke-width="3"/><path d="M152 28 A62 62 0 0 1 152 122" fill="none" stroke="#e8743b" stroke-width="6" opacity=".5"/><circle cx="100" cy="75" r="22" fill="#ffe0b8" stroke="#d97706" stroke-width="2.4"/><circle cx="100" cy="75" r="8" fill="#b45309"/></svg>`,
floaters:`<svg viewBox="0 0 200 150"><circle cx="100" cy="75" r="63" fill="#eef6ff" stroke="#0a3d8f" stroke-width="3"/><path d="M52 44 Q40 75 52 106" fill="#dff0ff" stroke="#1565d8" stroke-width="2"/><g fill="none" stroke="#334155" stroke-width="2.4" stroke-linecap="round" opacity=".7"><path d="M98 50 q12 6 5 18"/><circle cx="124" cy="88" r="4.5"/><path d="M82 96 q9 -5 16 2"/><circle cx="110" cy="64" r="3"/></g></svg>`,
opticnerve:`<svg viewBox="0 0 200 150"><circle cx="108" cy="75" r="56" fill="#fff" stroke="#0a3d8f" stroke-width="3"/><circle cx="108" cy="75" r="27" class="iris"/><circle cx="108" cy="75" r="11" class="pupil"/><path d="M52 75 Q20 75 12 58 M52 75 Q20 75 12 92" fill="none" stroke="#eab308" stroke-width="6" stroke-linecap="round"/><circle cx="52" cy="75" r="9" fill="#fde68a" stroke="#0a3d8f" stroke-width="2.4"/></svg>`,
retinadots:`<svg viewBox="0 0 200 150"><circle cx="100" cy="75" r="62" fill="#fdeede" stroke="#0a3d8f" stroke-width="3"/><circle cx="100" cy="75" r="10" fill="#fff2df" stroke="#d97706" stroke-width="2.4"/><g fill="#b91c1c"><circle cx="70" cy="54" r="4.5"/><circle cx="132" cy="58" r="4.5"/><circle cx="68" cy="98" r="4.5"/><circle cx="134" cy="94" r="4.5"/><circle cx="100" cy="38" r="3.6"/></g><path d="M100 75 Q72 60 58 64 M100 75 Q128 60 142 66" fill="none" stroke="#c2410c" stroke-width="2"/></svg>`,
};

/* ===== Pathologies ===== */
const P=[
{id:'cataracte',svg:SVG.cataracte,title:'Cataracte',short:"Opacification du cristallin",lead:"Le cristallin, la lentille naturelle de l'œil, devient progressivement opaque : la vision se voile, se ternit et devient sensible à l'éblouissement.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le cristallin est une lentille transparente située derrière la pupille. Avec le temps, ses protéines s'altèrent et il perd sa transparence. C'est un phénomène le plus souvent lié à l'âge, mais il peut être favorisé par le diabète, certains traitements (cortisone), un traumatisme ou une forte myopie.</p><h3>Les symptômes</h3><ul><li>Vision progressivement floue, comme un voile ou un brouillard</li><li>Éblouissement à la lumière, halos autour des phares la nuit</li><li>Couleurs qui paraissent ternes ou jaunies</li><li>Besoin de changer souvent de lunettes</li></ul><h3>Le diagnostic</h3><p>Un examen à la lampe à fente permet de voir l'opacification et d'en évaluer le retentissement. Des mesures précises (biométrie) préparent le choix de l'implant.</p><h3>Le traitement</h3><p>Il n'existe pas de collyre qui guérit la cataracte : le seul traitement est chirurgical. L'intervention, très courante et bien maîtrisée, retire le cristallin opacifié et le remplace par un <b>implant transparent</b> sur mesure. Elle se fait en ambulatoire, sous anesthésie locale (gouttes), en une quinzaine de minutes, sans douleur. La récupération est généralement rapide.</p><h3>Quand consulter</h3><p>Dès que la gêne visuelle retentit sur votre quotidien (conduite, lecture, travail). Il n'y a pas d'urgence à opérer : c'est le confort visuel qui guide la décision.</p>`},
{id:'glaucome',svg:SVG.glaucome,title:'Glaucome',short:"Atteinte silencieuse du nerf optique",lead:"Une maladie chronique du nerf optique, souvent liée à une pression intraoculaire trop élevée, qui évolue longtemps sans aucun symptôme.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le glaucome correspond à une destruction progressive des fibres du nerf optique. Le plus souvent, la pression à l'intérieur de l'œil est trop élevée car l'humeur aqueuse s'évacue mal. Le champ de vision se rétrécit lentement, en commençant par la périphérie, sans que la personne s'en rende compte.</p><h3>Les facteurs de risque</h3><ul><li>Âge supérieur à 40 ans</li><li>Antécédents familiaux de glaucome</li><li>Forte myopie, diabète, hypertension</li><li>Origine ethnique et cornée fine</li></ul><h3>Le diagnostic</h3><p>Il repose sur la mesure de la pression oculaire, l'examen du nerf optique, l'analyse des fibres (OCT) et le relevé du champ visuel. Ces examens sont indolores et rapides.</p><h3>Le traitement</h3><p>On ne récupère pas les fibres déjà perdues, mais on <b>stabilise</b> la maladie en abaissant la pression : collyres quotidiens, laser (trabéculoplastie, iridotomie) ou chirurgie selon les cas. Le suivi régulier est essentiel.</p><h3>Le message clé</h3><p>Parce qu'il est indolore et silencieux, le glaucome se dépiste : un contrôle régulier après 40 ans permet de le prendre à temps.</p>`},
{id:'glaucome-aigu',svg:SVG.glaucome,title:'Glaucome aigu (fermeture de l’angle)',short:"Une urgence : œil rouge et douloureux",lead:"Une élévation brutale et intense de la pression oculaire, provoquant une douleur vive : c'est une urgence ophtalmologique.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Contrairement au glaucome chronique, le glaucome aigu survient brutalement : l'angle par lequel s'évacue le liquide de l'œil se ferme d'un coup, et la pression grimpe très haut en quelques heures. Il touche surtout des yeux prédisposés (petits yeux, hypermétropes).</p><h3>Les signes d'alerte</h3><ul><li>Douleur oculaire intense, parfois avec maux de tête</li><li>Œil rouge, vision brutalement floue</li><li>Halos colorés autour des lumières</li><li>Parfois nausées et vomissements</li></ul><h3>Que faire ?</h3><p><b>Consultez en urgence sans attendre.</b> La prise en charge rapide (collyres, traitement pour faire baisser la pression, puis laser) permet d'éviter une perte de vision définitive.</p><h3>La prévention</h3><p>Chez les personnes à risque, un laser préventif (iridotomie) peut être proposé pour rouvrir la circulation et éviter la crise. En cas de doute, appelez le 04 97 19 30 46.</p>`},
{id:'dmla',svg:SVG.macula,title:'DMLA',short:"Dégénérescence maculaire liée à l'âge",lead:"Une atteinte de la macula, la zone centrale de la rétine responsable de la vision fine, fréquente après 50 ans.",html:`<h3>Qu'est-ce que c'est ?</h3><p>La macula permet de lire, de reconnaître les visages et de voir les détails. Avec l'âge, elle peut se dégrader. On distingue une forme <b>sèche</b> (évolution lente) et une forme <b>humide</b> (apparition de vaisseaux anormaux, évolution parfois rapide).</p><h3>Les symptômes</h3><ul><li>Déformation des lignes droites (une porte, un carrelage qui ondulent)</li><li>Tache floue ou sombre au centre de la vision</li><li>Baisse de la vision de près, besoin de plus de lumière</li></ul><h3>Le diagnostic</h3><p>L'examen du fond d'œil, l'OCT et parfois une angiographie précisent la forme et l'activité de la maladie. La grille d'Amsler permet une auto-surveillance simple à la maison.</p><h3>Le traitement</h3><p>La forme humide se traite par <b>injections intravitréennes</b>, aujourd'hui souvent espacées de 12 à 20 semaines grâce à de nouvelles molécules. La forme sèche relève surtout de la surveillance, de compléments adaptés et de mesures de prévention (arrêt du tabac).</p><h3>Le message clé</h3><p>Devant une déformation des lignes ou une tache centrale récente, <b>consultez rapidement</b> : plus la prise en charge est précoce, meilleur est le résultat.</p>`},
{id:'dpv',svg:SVG.floaters,title:'Décollement du vitré & corps flottants',short:"Les mouches volantes",lead:"Le gel qui remplit l'œil (le vitré) se rétracte avec l'âge et se décolle de la rétine : c'est très fréquent et le plus souvent bénin.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le vitré est un gel transparent. Avec le temps, il se liquéfie et se détache de la rétine (décollement postérieur du vitré). Ce phénomène naturel provoque l'apparition de corps flottants.</p><h3>Les symptômes</h3><ul><li>Points noirs, filaments ou « toiles d'araignée » qui bougent avec le regard</li><li>Parfois de brefs éclairs lumineux sur le côté</li></ul><h3>Pourquoi consulter ?</h3><p>Le plus souvent, c'est bénin. Mais au moment où le vitré se décolle, il peut <b>tirer sur la rétine et créer une déchirure</b>. C'est pourquoi une apparition récente de corps flottants ou d'éclairs justifie un <b>examen du fond d'œil</b> pour vérifier la rétine.</p><h3>La prise en charge</h3><p>S'il n'y a pas de déchirure, aucun traitement n'est nécessaire : les flottants s'atténuent avec le temps. En cas de déchirure, un laser au cabinet suffit souvent à la traiter et à éviter le décollement de rétine.</p>`},
{id:'decollement',svg:SVG.decollement,title:'Déchirure & décollement de rétine',short:"Une urgence ophtalmologique",lead:"Une déchirure de la rétine peut laisser le liquide passer dessous et la décoller de la paroi de l'œil : sans traitement rapide, la vision est menacée.",html:`<h3>Qu'est-ce que c'est ?</h3><p>La rétine tapisse le fond de l'œil comme une pellicule photo. Une déchirure permet au liquide de s'infiltrer et de la soulever : c'est le décollement de rétine. Les personnes fortement myopes, opérées de la cataracte ou ayant reçu un choc sont plus exposées.</p><h3>Les signes d'alerte</h3><ul><li>Pluie soudaine de corps flottants</li><li>Éclairs lumineux répétés</li><li>Voile, ombre ou rideau qui envahit une partie du champ de vision</li></ul><h3>Que faire ?</h3><p><b>Consultez en urgence.</b> Une déchirure seule se traite au <b>laser</b> au cabinet. Un décollement constitué nécessite une <b>chirurgie</b> (vitrectomie, parfois avec gaz), d'autant plus efficace qu'elle est réalisée tôt, surtout si la zone centrale n'est pas encore touchée.</p><h3>Le message clé</h3><p>Face à ces signes, chaque heure compte : appelez le 04 97 19 30 46 ou présentez-vous en urgence.</p>`},
{id:'retinopathie-diabetique',svg:SVG.retinadots,title:'Rétinopathie diabétique',short:"Le diabète et la rétine",lead:"Un diabète mal équilibré ou ancien peut abîmer les petits vaisseaux de la rétine, souvent sans aucun symptôme au début.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le sucre en excès fragilise la paroi des vaisseaux rétiniens : ils fuient, se bouchent, et de nouveaux vaisseaux anormaux peuvent apparaître. C'est une des principales causes de baisse de vision chez l'adulte, mais elle est largement évitable.</p><h3>Les symptômes</h3><ul><li>Souvent aucun au début — d'où l'importance du dépistage</li><li>Plus tard : vision fluctuante, floue, taches, baisse d'acuité</li></ul><h3>Le diagnostic</h3><p>Un <b>fond d'œil ou une imagerie de la rétine (rétinophotographie, OCT) une fois par an</b> permet de repérer les lésions avant qu'elles ne touchent la vision.</p><h3>Le traitement</h3><p>Le premier traitement est le <b>bon équilibre</b> du diabète, de la tension et du cholestérol. Selon les lésions : laser, injections intravitréennes, ou chirurgie dans les formes avancées.</p><h3>Le message clé</h3><p>Diabétique ? Un examen annuel de la rétine est indispensable, même si vous voyez parfaitement.</p>`},
{id:'occlusion-veineuse',svg:SVG.retinadots,title:'Occlusion veineuse rétinienne',short:"Une veine de la rétine se bouche",lead:"Le blocage d'une veine de la rétine entraîne un œdème et une baisse de vision, souvent brutale et indolore.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Comme une « phlébite » de l'œil, une veine rétinienne se bouche. Le sang stagne, la rétine gonfle (œdème maculaire), ce qui fait chuter la vision. C'est favorisé par l'hypertension, le diabète et le glaucome.</p><h3>Les symptômes</h3><ul><li>Baisse de vision brutale d'un œil, sans douleur</li><li>Vision déformée ou tache centrale</li></ul><h3>Le diagnostic</h3><p>Fond d'œil, OCT et parfois angiographie précisent l'étendue et l'œdème. Un bilan général (tension, diabète) est souvent nécessaire.</p><h3>Le traitement</h3><p>Les <b>injections intravitréennes</b> traitent efficacement l'œdème et améliorent la vision ; un laser peut compléter. Le contrôle des facteurs de risque protège l'autre œil.</p>`},
{id:'trou-maculaire',svg:SVG.macula,title:'Trou maculaire',short:"Une petite ouverture au centre de la rétine",lead:"Une déhiscence au centre de la macula, qui déforme et trouble la vision fine.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Au centre de la rétine, la macula peut se fragiliser et former un petit trou, souvent parce que le vitré tire dessus en se décollant. Il touche surtout les personnes de plus de 60 ans.</p><h3>Les symptômes</h3><ul><li>Vision centrale floue ou déformée</li><li>Tache au milieu du champ visuel</li><li>Difficulté à lire malgré des lunettes adaptées</li></ul><h3>Le diagnostic</h3><p>L'OCT, une imagerie en coupe de la rétine, visualise le trou avec précision et guide la décision.</p><h3>Le traitement</h3><p>Le traitement est chirurgical (<b>vitrectomie</b> avec pelage d'une fine membrane et bulle de gaz). Un <b>positionnement tête baissée</b> est souvent demandé quelques jours pour favoriser la fermeture. Opéré à temps, le résultat visuel est généralement bon.</p>`},
{id:'membrane-epiretinienne',svg:SVG.macula,title:'Membrane épirétinienne',short:"Une fine pellicule sur la macula",lead:"Une membrane translucide se forme à la surface de la macula et la plisse, déformant l'image.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Une très fine pellicule cellulaire se développe sur la rétine centrale et se contracte, comme une pellicule de cellophane qui froisse la macula. Elle est le plus souvent liée à l'âge.</p><h3>Les symptômes</h3><ul><li>Lignes droites qui paraissent ondulées</li><li>Vision centrale floue, images légèrement dédoublées</li><li>Gêne pour lire</li></ul><h3>Le diagnostic</h3><p>Le fond d'œil et surtout l'OCT montrent la membrane et le plissement de la macula.</p><h3>Le traitement</h3><p>Quand la gêne est modérée, une simple surveillance suffit. Si elle retentit sur la vision, une <b>chirurgie</b> (vitrectomie avec pelage de la membrane) permet de défroisser la macula. La récupération est progressive.</p>`},
{id:'hemorragie',svg:SVG.floaters,title:'Hémorragie intravitréenne',short:"Du sang dans le vitré",lead:"Un saignement à l'intérieur de l'œil qui trouble brutalement la vision.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Du sang se répand dans le gel vitréen et masque la rétine. Les causes fréquentes sont la rétinopathie diabétique, une déchirure de la rétine, une occlusion veineuse ou un traumatisme.</p><h3>Les symptômes</h3><ul><li>Apparition soudaine de nombreux corps flottants ou d'un voile rouge/noir</li><li>Baisse de vision brutale, indolore</li></ul><h3>Que faire ?</h3><p>Une baisse de vision brutale impose un <b>examen rapide</b> pour rechercher la cause, en particulier une déchirure de rétine à traiter d'urgence.</p><h3>Le traitement</h3><p>Selon la cause : laser, injections, ou <b>vitrectomie</b> pour retirer le sang si celui-ci ne se résorbe pas. On traite toujours la cause sous-jacente.</p>`},
{id:'keratocone',svg:SVG.keratocone,title:'Kératocône',short:"Déformation de la cornée en cône",lead:"La cornée s'amincit et se bombe en forme de cône, ce qui déforme progressivement la vision.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Normalement régulière, la cornée se fragilise et prend une forme conique irrégulière. Le kératocône débute souvent à l'adolescence et peut évoluer. Le frottement répété des yeux est un facteur aggravant reconnu.</p><h3>Les symptômes</h3><ul><li>Vision déformée, astigmatisme qui augmente vite</li><li>Changements fréquents de lunettes</li><li>Éblouissement, halos, vision double d'un œil</li></ul><h3>Le diagnostic</h3><p>La <b>topographie cornéenne</b> cartographie la cornée et détecte les formes débutantes. Un suivi régulier surveille l'évolution.</p><h3>Les traitements</h3><ul><li><b>Cross-linking</b> pour stabiliser une forme évolutive</li><li><b>Anneaux intracornéens</b> pour régulariser la cornée</li><li>Lentilles rigides adaptées, PKR topoguidée</li><li>Greffe de cornée dans les cas très avancés</li></ul><h3>Le conseil clé</h3><p>Ne vous frottez pas les yeux : c'est le meilleur geste de prévention.</p>`},
{id:'refraction',svg:SVG.refraction,title:'Myopie, hypermétropie, astigmatisme',short:"Quand l'image ne se forme pas sur la rétine",lead:"Selon la longueur de l'œil et la forme de la cornée, l'image se forme en avant, en arrière ou de façon déformée par rapport à la rétine.",html:`<h3>Les différents troubles</h3><ul><li><b>Myopie</b> : l'œil est trop long, la vision de loin est floue</li><li><b>Hypermétropie</b> : l'œil est trop court, fatigue visuelle et flou de près</li><li><b>Astigmatisme</b> : la cornée est irrégulière, l'image est déformée à toutes distances</li></ul><h3>Les symptômes</h3><p>Vision floue, plissement des yeux, maux de tête, fatigue visuelle sur écran, difficultés à conduire la nuit.</p><h3>Le diagnostic</h3><p>Un examen de la vue mesure précisément la correction ; un bilan complet vérifie la santé de l'œil.</p><h3>Les solutions</h3><p>Lunettes, lentilles de contact, ou <b>chirurgie réfractive au laser</b> pour se libérer des corrections. La forte myopie justifie une surveillance de la rétine.</p>`},
{id:'presbytie',svg:SVG.refraction,title:'Presbytie',short:"La vision de près après 45 ans",lead:"Avec l'âge, l'œil perd sa capacité à faire la mise au point de près : c'est un phénomène naturel et universel.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le cristallin perd de sa souplesse à partir de 45 ans environ : il devient plus difficile de lire de près. La presbytie n'est pas une maladie, mais une évolution normale.</p><h3>Les symptômes</h3><ul><li>Besoin d'éloigner les textes pour les lire</li><li>Fatigue à la lecture, en faible lumière</li><li>Difficulté à passer de la vision de loin à celle de près</li></ul><h3>Les solutions</h3><p>Lunettes de lecture ou verres progressifs, lentilles adaptées, et parfois <b>chirurgie</b> (laser presbytie, ou implants multifocaux lors d'une chirurgie de la cataracte). Le choix dépend de votre mode de vie et d'un bilan personnalisé.</p>`},
{id:'lasik',svg:SVG.laser,title:'Chirurgie laser réfractive',short:"LASIK, PKR, SMILE",lead:"Le laser remodèle la cornée pour corriger la myopie, l'hypermétropie, l'astigmatisme et la presbytie, et se libérer des lunettes.",html:`<h3>Le principe</h3><p>Le laser modifie très précisément la courbure de la cornée afin que les rayons lumineux se focalisent sur la rétine. Plusieurs techniques existent : <b>LASIK</b> (récupération très rapide), <b>PKR</b> (laser de surface, idéal pour les cornées fines), <b>SMILE</b> (mini-invasif, sans capot).</p><h3>Suis-je opérable ?</h3><p>Cela dépend de votre correction, de l'épaisseur et de la régularité de votre cornée, et de votre âge. Un <b>bilan pré-opératoire complet</b> (topographie, mesures) détermine la technique la plus sûre — ou déconseille l'intervention si elle n'est pas adaptée.</p><h3>Le déroulé</h3><p>L'intervention dure quelques minutes par œil, sans douleur pendant l'acte. La récupération est souvent de 24 à 48 h pour le LASIK, un peu plus progressive pour la PKR.</p><h3>Après</h3><p>Collyres, protection des yeux, pas de frottement ni de piscine quelque temps. Un suivi contrôle la cicatrisation.</p>`},
{id:'strabisme',svg:SVG.strabisme,title:'Strabisme',short:"Un défaut d'alignement des yeux",lead:"Les deux yeux ne regardent pas dans la même direction : un œil dévie vers l'intérieur, l'extérieur, le haut ou le bas.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le strabisme est un défaut de parallélisme des yeux. Chez l'enfant, il peut entraîner une « paresse » visuelle (amblyopie) s'il n'est pas pris en charge tôt. Chez l'adulte, il peut apparaître et provoquer une vision double.</p><h3>Les signes</h3><ul><li>Un œil qui dévie, de façon permanente ou intermittente</li><li>Chez l'enfant : tête penchée, œil qui « part »</li><li>Chez l'adulte : vision double</li></ul><h3>La prise en charge</h3><p>Bilan orthoptique complet, correction optique adaptée, cache pour rééduquer l'œil paresseux chez l'enfant, et si besoin <b>chirurgie</b> des muscles oculomoteurs pour réaligner les yeux.</p><h3>Le message clé</h3><p>Le <b>dépistage précoce chez l'enfant</b> est déterminant : plus la prise en charge est tôt, meilleurs sont les résultats.</p>`},
{id:'nystagmus',svg:SVG.opticnerve,title:'Nystagmus',short:"Des mouvements involontaires des yeux",lead:"Les yeux animés de petites oscillations involontaires et rythmiques, souvent présentes dès l'enfance.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le nystagmus est un mouvement involontaire des yeux, horizontal, vertical ou rotatoire. Il peut être congénital (présent tôt dans la vie) ou acquis (lié à une cause neurologique ou de l'oreille interne).</p><h3>Les conséquences</h3><ul><li>Baisse de l'acuité visuelle</li><li>Position de tête compensatrice</li><li>Parfois sensation d'instabilité des images (surtout dans les formes acquises)</li></ul><h3>Le bilan</h3><p>Un examen ophtalmologique complet recherche une cause oculaire ; un bilan complémentaire (neurologique) est parfois nécessaire, surtout pour un nystagmus apparu récemment.</p><h3>La prise en charge</h3><p>Correction optique optimale, parfois prismes ou chirurgie pour améliorer la position de tête. Un nystagmus <b>d'apparition récente</b> chez un adulte doit être exploré sans tarder.</p>`},
{id:'neuropathie',svg:SVG.opticnerve,title:'Neuropathie optique',short:"Une souffrance du nerf optique",lead:"Une atteinte du nerf optique, le « câble » qui relie l'œil au cerveau, pouvant faire chuter la vision.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le nerf optique transmet les images au cerveau. Il peut souffrir d'une inflammation (névrite optique), d'un manque de circulation, d'une compression ou d'une cause toxique. Selon la cause, l'atteinte est brutale ou progressive.</p><h3>Les symptômes</h3><ul><li>Baisse de vision d'un œil, souvent rapide</li><li>Altération des couleurs (elles paraissent délavées)</li><li>Parfois douleur à la mobilisation de l'œil</li></ul><h3>Le diagnostic</h3><p>Examen du fond d'œil, champ visuel, OCT du nerf, et souvent un bilan complémentaire (imagerie cérébrale, prise de sang) pour identifier la cause.</p><h3>La prise en charge</h3><p>Elle dépend entièrement de la cause. Une baisse de vision rapide et inexpliquée d'un œil doit conduire à une <b>consultation sans délai</b>.</p>`},
{id:'conjonctivite',svg:SVG.redeye,title:'Conjonctivite',short:"L'œil rouge le plus fréquent",lead:"Une inflammation de la conjonctive, la fine membrane qui recouvre le blanc de l'œil : très fréquente et le plus souvent bénigne.",html:`<h3>Qu'est-ce que c'est ?</h3><p>La conjonctivite peut être <b>virale</b> (souvent contagieuse), <b>bactérienne</b>, ou <b>allergique</b>. Elle rend l'œil rouge et inconfortable, sans habituellement baisser la vision.</p><h3>Les symptômes</h3><ul><li>Œil rouge, sensation de sable, larmoiement</li><li>Sécrétions (claires si virale/allergique, jaunes si bactérienne)</li><li>Démangeaisons marquées si allergie, souvent des deux yeux</li></ul><h3>Les conseils</h3><p>Lavage des mains, ne pas se frotter les yeux, éviter le maquillage et les lentilles le temps de la guérison. Compresses et larmes artificielles soulagent.</p><h3>Quand consulter</h3><p>La plupart guérissent seules. Consultez en cas de <b>douleur vraie, baisse de vision, forte photophobie</b> ou si les symptômes persistent : d'autres causes plus sérieuses doivent être écartées.</p>`},
{id:'uveite',svg:SVG.redeye,title:'Uvéite',short:"Inflammation à l'intérieur de l'œil",lead:"Une inflammation de l'uvée, la couche vasculaire de l'œil, qui peut menacer la vision si elle n'est pas traitée.",html:`<h3>Qu'est-ce que c'est ?</h3><p>À la différence de la conjonctivite, l'uvéite est une inflammation <b>interne</b> de l'œil. Elle peut être isolée ou associée à une maladie générale (inflammatoire ou infectieuse).</p><h3>Les symptômes</h3><ul><li>Œil rouge et douloureux</li><li>Photophobie (gêne à la lumière)</li><li>Baisse de vision, parfois corps flottants</li></ul><h3>Le diagnostic</h3><p>L'examen à la lampe à fente confirme l'inflammation. Selon les cas, un bilan général recherche une cause.</p><h3>Le traitement</h3><p>Il repose sur des <b>collyres anti-inflammatoires</b> (souvent corticoïdes) et dilatateurs, parfois un traitement général. Une prise en charge rapide évite les complications (glaucome, cataracte, atteinte de la rétine).</p>`},
{id:'secheresse',svg:SVG.redeye,title:'Sécheresse oculaire',short:"Yeux qui piquent et fatiguent",lead:"Un manque ou une mauvaise qualité des larmes, très fréquent, souvent aggravé par les écrans et l'environnement.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le film lacrymal protège et lubrifie la surface de l'œil. Quand il est insuffisant ou de mauvaise qualité, la surface s'irrite. Les écrans (on cligne moins), la climatisation, l'âge et certains médicaments favorisent la sécheresse.</p><h3>Les symptômes</h3><ul><li>Picotements, sensation de sable ou de brûlure</li><li>Yeux fatigués, vision qui fluctue en fin de journée</li><li>Larmoiement réflexe paradoxal</li></ul><h3>Les conseils</h3><p>Cligner volontairement, faire des pauses régulières devant les écrans, aérer, s'hydrater, et utiliser des <b>larmes artificielles</b>. Le soin des paupières aide souvent.</p><h3>Quand consulter</h3><p>Si la gêne persiste, un examen recherche la cause (paupières, glandes) et adapte le traitement.</p>`},
{id:'chalazion',svg:SVG.eyelid,title:'Chalazion',short:"Une boule dans la paupière",lead:"Un petit kyste inflammatoire de la paupière, dû à l'obstruction d'une glande, sans gravité mais parfois gênant.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le chalazion est provoqué par le bouchage d'une glande de la paupière (glande de Meibomius). La sécrétion s'accumule et forme une boule ferme, parfois rouge et sensible.</p><h3>Les symptômes</h3><ul><li>Tuméfaction ronde et ferme sur la paupière</li><li>Rougeur et gêne, sans réelle douleur intense</li><li>Parfois vision temporairement gênée s'il appuie sur l'œil</li></ul><h3>Le traitement</h3><p>Des <b>soins locaux</b> sont très efficaces : compresses chaudes plusieurs fois par jour et massage doux de la paupière pour vider la glande, souvent associés à une pommade. S'il persiste plusieurs semaines, une petite <b>incision</b> au cabinet peut être proposée.</p><h3>La prévention</h3><p>Une bonne hygiène des paupières limite les récidives, surtout en cas de blépharite.</p>`},
{id:'orgelet',svg:SVG.eyelid,title:'Orgelet',short:"Un « bouton » au bord du cil",lead:"Une infection aiguë d'une glande à la base d'un cil : douloureux mais généralement bénin et rapide à guérir.",html:`<h3>Qu'est-ce que c'est ?</h3><p>L'orgelet est un petit abcès au bord de la paupière, centré sur un cil, provoqué par une bactérie. Il ressemble à un bouton rouge et douloureux.</p><h3>Les symptômes</h3><ul><li>Bord de paupière rouge, gonflé et douloureux</li><li>Petit point blanc au centre</li><li>Larmoiement, gêne</li></ul><h3>Le traitement</h3><p><b>Compresses chaudes</b> plusieurs fois par jour, hygiène des mains et des paupières. Une pommade antibiotique est parfois prescrite. Il ne faut <b>pas percer</b> soi-même l'orgelet.</p><h3>Quand consulter</h3><p>Si l'infection s'étend à toute la paupière, si l'œil devient rouge et douloureux, ou en l'absence d'amélioration, une consultation est conseillée.</p>`},
{id:'pterygion',svg:SVG.redeye,title:'Ptérygion',short:"Un voile qui gagne la cornée",lead:"Une excroissance de la conjonctive, en forme d'aile, qui progresse depuis le coin de l'œil vers la cornée.",html:`<h3>Qu'est-ce que c'est ?</h3><p>Le ptérygion est un épaississement de la conjonctive, favorisé par l'exposition au soleil (UV), au vent et à la poussière. Il avance lentement sur la cornée, surtout dans les régions ensoleillées comme la Côte d'Azur.</p><h3>Les symptômes</h3><ul><li>Voile charnu, rosé, au coin interne de l'œil</li><li>Rougeur, sensation de corps étranger</li><li>Astigmatisme ou baisse de vision s'il atteint le centre de la cornée</li></ul><h3>Le traitement</h3><p>Tant qu'il est petit et calme : protection solaire, larmes artificielles. S'il progresse, gêne la vision ou s'enflamme souvent, une <b>ablation chirurgicale</b> (avec greffe conjonctivale pour limiter les récidives) est proposée.</p><h3>La prévention</h3><p>Portez des <b>lunettes de soleil</b> filtrant les UV, surtout en extérieur.</p>`},
{id:'pinguecula',svg:SVG.redeye,title:'Pinguécula',short:"Une petite tache jaunâtre sur le blanc",lead:"Un épaississement bénin de la conjonctive, jaunâtre, sur le blanc de l'œil, lié surtout au soleil.",html:`<h3>Qu'est-ce que c'est ?</h3><p>La pinguécula est un dépôt bénin sur la conjonctive, à côté de la cornée, sans l'envahir (contrairement au ptérygion). Elle est favorisée par les UV, le vent et la sécheresse.</p><h3>Les symptômes</h3><ul><li>Petite surélévation jaunâtre sur le blanc de l'œil</li><li>Parfois rougeur et irritation quand elle s'enflamme (pinguéculite)</li></ul><h3>Le traitement</h3><p>Le plus souvent, aucune prise en charge n'est nécessaire. En cas d'irritation : larmes artificielles et, si elle s'enflamme, un collyre anti-inflammatoire. L'<b>ablation</b> reste rare, surtout pour raison esthétique ou gêne.</p><h3>La prévention</h3><p>La protection solaire et l'hydratation de la surface oculaire limitent son évolution.</p>`},
{id:'corps-etranger',svg:SVG.redeye,title:'Corps étranger',short:"Une poussière ou un éclat dans l'œil",lead:"Un grain, un éclat ou une particule sur la surface de l'œil : fréquent, souvent bénin, mais parfois à retirer par un professionnel.",html:`<h3>Ce qui se passe</h3><p>Une poussière, un cil, un grain de métal ou de bois se dépose sur la conjonctive ou la cornée. La gêne est immédiate et l'œil larmoie pour l'évacuer.</p><h3>Les symptômes</h3><ul><li>Sensation de grain de sable, gêne à chaque clignement</li><li>Larmoiement, rougeur, difficulté à ouvrir l'œil</li></ul><h3>Les bons gestes</h3><p>Ne pas frotter l'œil. Cligner, rincer abondamment au sérum physiologique ou à l'eau claire. Si le corps étranger part, la gêne cède rapidement.</p><h3>Quand consulter en urgence</h3><p>Si le corps étranger <b>reste fiché</b>, s'il est métallique, projeté à grande vitesse (meulage, bricolage), ou si la douleur et la baisse de vision persistent : <b>consultez en urgence</b>. Ne tentez pas de le retirer vous-même. Urgences SOS Œil : 04 97 19 30 46.</p>`},
];

/* ===== Rendu ===== */
function el(html){const d=document.createElement('div');d.innerHTML=html;return d.firstElementChild;}
heroChatDemo();
const pgrid=document.getElementById('pgrid');
P.forEach(p=>{
const c=el(`<div class="pcard"><div class="thumb">${p.svg}</div><div class="body"><h3>${p.title}</h3><p>${p.short}</p><div class="more">En savoir plus →</div></div></div>`);
c.onclick=()=>openDetail(p.id);pgrid.appendChild(c);
});
function openDetail(id){const p=P.find(x=>x.id===id);if(!p)return;
document.getElementById('dstage').innerHTML=p.svg;
document.getElementById('dcontent').innerHTML=`<h1>${p.title}</h1><p class="lead">${p.lead}</p>${p.html}<div style="margin-top:1.6rem"><a class="btn btn-primary" href="https://www.doctolib.fr/cabinet-medical/nice/m-eye-clinic" target="_blank" rel="noopener">Prendre rendez-vous</a></div>`;
go('detail');scrollTo(0,0);
}
/* ===== Navigation ===== */
function go(v){document.querySelectorAll('.view').forEach(s=>s.classList.remove('active'));document.getElementById(v).classList.add('active');
document.querySelectorAll('.menu a[data-v]').forEach(a=>a.classList.toggle('on',a.dataset.v===v));
document.getElementById('menu').classList.remove('open');
if(v==='chat')setTimeout(()=>document.getElementById('input').focus(),100);}
window.go=go;

/* ===== Chat ===== */
const msgsEl=document.getElementById('msgs');let history=[];
const suggestions=["Comment se passe l'opération de la cataracte ?","Suis-je opérable au laser ?","Que faire après mon injection (IVT) ?","Quand consulter en urgence ?"];
const sg=document.getElementById('suggest');
suggestions.forEach(s=>{const c=el(`<span class="chip">${s}</span>`);c.onclick=()=>{document.getElementById('input').value=s;send()};sg.appendChild(c);});
function fmt(t){return t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>');}
function addMsg(role,text){const m=el(`<div class="msg ${role==='user'?'u':'a'}">${role==='user'?fmt(text):text}</div>`);msgsEl.appendChild(m);msgsEl.scrollTop=msgsEl.scrollHeight;return m;}
if(!msgsEl.children.length)addMsg('assistant',"Bonjour 👋 Je suis l'assistant de M'Eye Clinic. Posez-moi vos questions sur vos yeux, vos examens ou votre opération. <i style='color:#94a3b8'>(Je donne des informations générales, je ne remplace pas votre médecin.)</i>");
async function send(){
const inp=document.getElementById('input');const text=inp.value.trim();if(!text)return;
inp.value='';document.getElementById('suggest').style.display='none';
addMsg('user',text);history.push({role:'user',content:text});
const wait=addMsg('assistant',"<i style='color:#94a3b8'>L'assistant réfléchit…</i>");
try{
const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history})});
const data=await r.json();
const reply=(data&&data.reply)?data.reply:"Désolé, une erreur est survenue. Réessayez ou appelez le 04 97 19 30 46.";
wait.innerHTML=fmt(reply);history.push({role:'assistant',content:reply});msgsEl.scrollTop=msgsEl.scrollHeight;
}catch(e){wait.innerHTML="Connexion impossible pour le moment. Réessayez, ou appelez le <b>04 97 19 30 46</b>.";}
}
window.send=send;

/* ===== Hero : conversation animée « Assistant en action » ===== */
function heroChatDemo(){
var stage=document.getElementById('heroStage');
if(!stage)return;
stage.style.display='block';stage.style.padding='0';
var css=".hx-card{background:#fff;border-radius:16px;width:100%;height:100%;display:flex;flex-direction:column;overflow:hidden;font-family:'Inter',system-ui,sans-serif}"
+".hx-head{display:flex;align-items:center;gap:10px;padding:13px 16px;border-bottom:1px solid #e4e8f1;flex:none}"
+".hx-av{width:38px;height:38px;border-radius:50%;background:#eaf1fb;display:flex;align-items:center;justify-content:center;flex:none}"
+".hx-av svg{width:24px;height:24px}"
+".hx-name{font-weight:700;color:#1f4e86;font-size:14.5px;line-height:1.1}"
+".hx-status{font-size:11px;color:#1aa37a;display:flex;align-items:center;gap:5px;margin-top:2px}"
+".hx-dot{width:7px;height:7px;border-radius:50%;background:#1aa37a;animation:hxpulse 2s infinite}"
+"@keyframes hxpulse{0%{box-shadow:0 0 0 0 rgba(26,163,122,.5)}70%{box-shadow:0 0 0 7px rgba(26,163,122,0)}100%{box-shadow:0 0 0 0 rgba(26,163,122,0)}}"
+".hx-body{flex:1;padding:14px 14px 8px;display:flex;flex-direction:column;justify-content:flex-start;overflow:hidden;background:#f5f9ff}"
+".hx-row{display:flex;margin:7px 0;align-items:flex-end;gap:8px;opacity:0;transform:translateY(14px);transition:opacity .45s ease,transform .45s ease}"
+".hx-row.show{opacity:1;transform:none}"
+".hx-row.me{justify-content:flex-end}"
+".hx-bub{max-width:82%;padding:10px 13px;font-size:13px;line-height:1.42;border-radius:16px}"
+".hx-row.me .hx-bub{background:#1f4e86;color:#fff;border-bottom-right-radius:5px}"
+".hx-row.bot .hx-bub{background:#eaf1fb;color:#172033;border-bottom-left-radius:5px}"
+".hx-mini{width:24px;height:24px;border-radius:50%;background:#eaf1fb;display:flex;align-items:center;justify-content:center;flex:none}"
+".hx-mini svg{width:16px;height:16px}"
+".hx-typing .hx-bub{display:flex;gap:5px;align-items:center}"
+".hx-typing i{width:6px;height:6px;border-radius:50%;background:#9aa6b6;display:inline-block;animation:hxblink 1.2s infinite}"
+".hx-typing i:nth-child(2){animation-delay:.2s}.hx-typing i:nth-child(3){animation-delay:.4s}"
+"@keyframes hxblink{0%,80%,100%{opacity:.3}40%{opacity:1}}";
var stEl=document.createElement('style');stEl.textContent=css;document.head.appendChild(stEl);
var eyeAv='<svg viewBox="0 0 32 32"><ellipse cx="16" cy="16" rx="13" ry="8.5" fill="none" stroke="#1f4e86" stroke-width="2.4"/><circle cx="16" cy="16" r="4.6" fill="#2888c4"/><circle cx="16" cy="16" r="1.7" fill="#13325c"/></svg>';
var miniAv='<svg viewBox="0 0 32 32"><ellipse cx="16" cy="16" rx="13" ry="8.5" fill="none" stroke="#1f4e86" stroke-width="2.4"/><circle cx="16" cy="16" r="4.6" fill="#2888c4"/></svg>';
stage.innerHTML='<div class="hx-card"><div class="hx-head"><div class="hx-av">'+eyeAv+'</div><div><div class="hx-name">Assistant M\'Eye Clinic</div><div class="hx-status"><span class="hx-dot"></span>En ligne · répond 24h/24</div></div></div><div class="hx-body" id="hxBody"></div></div>';
var body=document.getElementById('hxBody');
var PAIRS=[
{q:"Après mon opération de la cataracte, quand puis-je conduire ?",a:"Souvent dès que votre chirurgien l'autorise et que la vision est nette 👍 Je vous donne les repères des premiers jours ?"},
{q:"C'est quoi une chirurgie au laser (LASIK) ?",a:"Une correction de la vue en quelques minutes, sans douleur pendant l'acte 👨‍⚕️ Récupération souvent en 24–48 h ✨"},
{q:"J'ai des mouches et des éclairs, est-ce grave ?",a:"Mieux vaut faire vérifier votre rétine rapidement 👀 Je peux vous orienter vers un créneau d'urgence."},
{q:"Suis-je trop âgé pour être opéré de la cataracte ?",a:"Pas d'âge limite 🙂 L'opération se fait à 70, 80, 90 ans avec d'excellents résultats 👨‍⚕️👍"},
{q:"Quand dois-je mettre mes collyres après l'opération ?",a:"Suivez le rythme de l'ordonnance 💧 Pensez à espacer chaque collyre de quelques minutes. À très vite 😊"},
{q:"Peut-on se faire opérer au laser à tout âge ?",a:"La chirurgie laser corrige aujourd'hui toutes les amétropies — myopie, hypermétropie, astigmatisme et presbytie 👨‍⚕️ Elle se pratique en général de 18 à 60 ans, après un bilan personnalisé ✨"}
];
function wait(ms){return new Promise(function(r){setTimeout(r,ms);});}
function rowMe(t){var r=document.createElement('div');r.className='hx-row me';r.innerHTML='<div class="hx-bub">'+t+'</div>';body.appendChild(r);requestAnimationFrame(function(){r.classList.add('show');});return r;}
function rowTyping(){var r=document.createElement('div');r.className='hx-row bot hx-typing';r.innerHTML='<div class="hx-mini">'+miniAv+'</div><div class="hx-bub"><i></i><i></i><i></i></div>';body.appendChild(r);requestAnimationFrame(function(){r.classList.add('show');});return r;}
function rowBot(t){var r=document.createElement('div');r.className='hx-row bot';r.innerHTML='<div class="hx-mini">'+miniAv+'</div><div class="hx-bub">'+t+'</div>';body.appendChild(r);requestAnimationFrame(function(){r.classList.add('show');});return r;}
function fadeClear(){return new Promise(function(res){var kids=body.children,k;for(k=0;k<kids.length;k++)kids[k].classList.remove('show');setTimeout(function(){body.innerHTML='';res();},450);});}
var i=0;
async function loop(){
while(true){
var p=PAIRS[i%PAIRS.length];
rowMe(p.q); await wait(1100);
var t=rowTyping(); await wait(1500); t.remove();
rowBot(p.a); await wait(4200);
await fadeClear(); await wait(350);
i++;
}
}
loop();
}
